# Generated by Django 3.2.7 on 2021-09-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechnoWorld', '0002_alter_content_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='img1',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
