# Generated by Django 3.2.7 on 2021-09-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechnoWorld', '0003_content_img1'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=500)),
            ],
        ),
    ]
